// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmjHKWrFgl2ZT_mCgiXJ-f6YHoGLffHs',
    appId: '1:117409029742:web:5e2f0c6653d6e5f5dad07f',
    messagingSenderId: '117409029742',
    projectId: 'dalel-fb80b',
    authDomain: 'dalel-fb80b.firebaseapp.com',
    storageBucket: 'dalel-fb80b.firebasestorage.app',
    measurementId: 'G-JW8CVTY67E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GZbSGEoJERXaui0ykanoR4jmoTd8LDI',
    appId: '1:117409029742:android:880f3b3eb1486550dad07f',
    messagingSenderId: '117409029742',
    projectId: 'dalel-fb80b',
    storageBucket: 'dalel-fb80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cj-bpMPj0UsVxPExYx9Bda9dAFhTvfk',
    appId: '1:117409029742:ios:90ef12461b0c6338dad07f',
    messagingSenderId: '117409029742',
    projectId: 'dalel-fb80b',
    storageBucket: 'dalel-fb80b.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4cj-bpMPj0UsVxPExYx9Bda9dAFhTvfk',
    appId: '1:117409029742:ios:90ef12461b0c6338dad07f',
    messagingSenderId: '117409029742',
    projectId: 'dalel-fb80b',
    storageBucket: 'dalel-fb80b.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdmjHKWrFgl2ZT_mCgiXJ-f6YHoGLffHs',
    appId: '1:117409029742:web:e91646212d02c949dad07f',
    messagingSenderId: '117409029742',
    projectId: 'dalel-fb80b',
    authDomain: 'dalel-fb80b.firebaseapp.com',
    storageBucket: 'dalel-fb80b.firebasestorage.app',
    measurementId: 'G-X359K5DTHZ',
  );
}
